logging:
  level:
    org:
      springframework:
        web=DEBUG
server:
  port: 8080
  contextPath: /issuetracker


spring:
  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    url: jdbc:h2:file:~/simple-ticket-db
    username: sa
    password:
    driver-class-name: org.h2.Driver
    max-active: 10
    max-idle: 8
    max-wait: 10000
    min-evictable-idle-time-millis: 1000
    min-idle: 8
    time-between-eviction-run-millis: 1

  jpa:
    hibernate:
        ddl-auto: false

flyway:
  baseline-on-migrate: true
