package au.com.domain.demo.entity;

import javax.persistence.*;

/**
 * Created by mseskander .
 */
@Entity
@Table(name="CommentRepository")
public class Comment {
    /*
    -- Here are the required script to create the CommentRepository table
    -- Create the table
        CREATE TABLE COMMENT (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY,
          description varchar(2000) not null,
          user_id BIGINT not null,
          issue_id BIGINT not null
        );
    -- Add forign keys
        ALTER TABLE COMMENT ADD FOREIGN KEY (issue_id) REFERENCES ISSUE(id);
        ALTER TABLE ISSUE_TRACKER.ISSUE ADD FOREIGN KEY (user_id) REFERENCES USER(id);
     */

    //relationship
    //@ManyToOne //with issue table
    //@OneToOne //with user table
    @Id
    @GeneratedValue(strategy= GenerationType.IDENTITY)
    private Long id;

    private Long user_id;

    private Long issue_id;

    private String comment;

    public Comment() {}

    public Comment(Long id, Long user_id, Long issue_id, String comment) {
        this.id = id;
        this.user_id = user_id;
        this.issue_id = issue_id;
        this.comment = comment;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getUser_id() {
        return user_id;
    }

    public void setUser_id(Long user_id) {
        this.user_id = user_id;
    }

    public Long getIssue_id() {
        return issue_id;
    }

    public void setIssue_id(Long issue_id) {
        this.issue_id = issue_id;
    }

    public String getComment() {
        return comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }
}